### ISSUE TITLE
枚举管理中存在的bug

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_client#10]
# bug 描述及触发
新建一个枚举1， 删除枚举1， 再新建枚举1，
会因为缓存创建失败

# 正常行为
删除枚举后，应该完全删除，不应该出现创建不出来的情况。
且，建议不要以自己输入的值作为key，应该给它一个unique key？用户可自行去删除重复的枚举？

**Comment by zhuyuwaiting** [comment]
done
