### ISSUE TITLE
枚举管理简化添加步骤

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_client#13]
现在新建枚举时需要填写：
- 值
- 值名称
- 值描述

三都均带 *号，为必填项，且每次均需要保证【值】不一样。

简化后：
- 值名称
- 值描述（选填）
去掉【值】的手动填写，改为自动生成unique值，将值描述变为选填项。

**Comment by zhuyuwaiting** [comment]
fix
