### ISSUE TITLE
新建西药需添加新的枚举项

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_client#17]
当前表单：
药品名称：头孢
基础重量： 0.1
药品组成单位： g
基础组成数量： 12
药品单位： 盒
……

经过上述填写之后，会显示 0.10g*12 / 盒

===========

但是实际上需要：
0.1gx12片/盒
<== 注意这个片字

因此，还需要添加一项【妈的叫什么名字比较好你想一想我想不出来】
作为枚举项。
从而可以添加这个【片、粒、支】字

经协商，
【50mg x 5粒/板 x 2板/ 盒】 这个奇怪的需要简化写成 【50mg x 10粒/盒】
因此还是加个粒就OK

**Comment by zhuyuwaiting** [comment]
fix
