### ISSUE TITLE
中药管理需要中添默认数量

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_client#8]
现在的情况：
【中药管理】-> 【新建药品】中需要填写的信息：
- 药品名称：当归
- 药品单位：克
- 服用方式：煎服

更改后的情况：
【中药管理】->【新建药品】
- 药品名称：当归
- 药品数量：50  <==== 新增加这一行
- 药品单位：克
- 服用方式：煎服

===============
备注：
- 这里的药品数量与【新建处方】->【添加药品】处的药品数量是否是同一个？
- 是同一个
（因此我觉得这里是在新建药品的时候需要添加一个默认数量，这个数量在开处方、添加药品的过程中仍然可修改，但是有一个默认值）。
===============
原话：
- 中药管理……药品单位前面，可设置药品数量？
- 即新建药品中的药品单位前面，可否设置药品数量？
    - 那里也可以加
    - 但是加了就是，新建处方、药品管理的地方，都会有数量
    - 这两个数量是同一个吗
- 是同一个吧

**Comment by zhuyuwaiting** [comment]
done
