### ISSUE TITLE
枚举管理中添加用药频次

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_client#9]
原文：
- 枚举管理……名称中，能否加用药频次？如:每天一次，每八小时一次，每二次一小时，每12小时一次，等等。
         - 【用药频次】 是在 【中药管理】、【西药管理】中都需要加对吧 ？
- 西药管理里。
- 中草药不用

================
现在的情况：
【西药管理】->【创建药品】：
- 每日次数：3

更改后：
【西药管理】->【创建药品】：
- 用药频次：（下拉选项：每天一次，每天3次，每8小时1次，每12小时1次等）
（注意，名字也发生了更改， "每日次数" -> "用药频次" )

**Comment by zhuyuwaiting** [comment]
done
